apiVersion: v1
kind: Service
metadata:
  name: bored
spec:
  selector:
    app: bored
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bored-nodeport
spec:
  type: NodePort
  selector:
    app: bored
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
